apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-service-rollouts
  namespace: argocd
spec:
  destination:
    namespace: echo-service-rollouts
    server: "https://192.168.2.43:55382"
  project: default
  source:
    path: echo-service-mainfest-rollouts/blue-green
    repoURL: "https://github.com/nahidupa/echo-service-manifest.git"
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
